"""Creates freight table

Revision ID: 4f06d46925e7
Revises: 7c4814832e06
Create Date: 2023-05-25 02:39:30.295478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f06d46925e7'
down_revision = '7c4814832e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FREIGHT',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('contractor', sa.String(length=60), nullable=False),
    sa.Column('cargo_weight', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('agreed_payment', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('distance', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_city', sa.String(length=50), nullable=True),
    sa.Column('origin_state', sa.CHAR(length=2), nullable=True),
    sa.Column('origin_country', sa.String(length=50), nullable=True),
    sa.Column('origin_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('origin_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destination_city', sa.String(length=50), nullable=True),
    sa.Column('destination_state', sa.CHAR(length=2), nullable=True),
    sa.Column('destination_country', sa.String(length=50), nullable=True),
    sa.Column('destination_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destination_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('truck_driver_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['truck_driver_id'], ['TRUCK_DRIVER.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FREIGHT')
    # ### end Alembic commands ###
