"""creates_categories_table

Revision ID: 75f22274ae02
Revises: 8ff7686ccd6f
Create Date: 2023-07-12 04:40:17.849494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f22274ae02'
down_revision = '8ff7686ccd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CATEGORY',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('truck_driver_id', sa.BigInteger(), nullable=False),
    sa.Column('identifier', sa.String(length=36), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['truck_driver_id'], ['TRUCK_DRIVER.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('CATEGORY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CATEGORY_identifier'), ['identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_CATEGORY_truck_driver_id'), ['truck_driver_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CATEGORY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CATEGORY_truck_driver_id'))
        batch_op.drop_index(batch_op.f('ix_CATEGORY_identifier'))

    op.drop_table('CATEGORY')
    # ### end Alembic commands ###
