"""Adds identifier and synced_at to freights

Revision ID: 8ff7686ccd6f
Revises: 40926f2ea3a5
Create Date: 2023-06-11 22:18:59.998398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff7686ccd6f'
down_revision = '40926f2ea3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FREIGHT', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_FREIGHT_identifier'), ['identifier'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FREIGHT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_FREIGHT_identifier'))
        batch_op.drop_column('synced_at')
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
