"""Adds category relationship to accounts

Revision ID: c93555bc419a
Revises: 2c0994f3037a, 75f22274ae02
Create Date: 2023-07-16 01:06:06.706336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93555bc419a'
down_revision = ('2c0994f3037a', '75f22274ae02')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACCOUNT', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.BigInteger(), nullable=False))
        batch_op.create_index(batch_op.f('ix_ACCOUNT_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'CATEGORY', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACCOUNT', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ACCOUNT_category_id'))
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
