"""Adds unique constraint to name and freight ID in Account

Revision ID: dc5d7a9b7750
Revises: c93555bc419a
Create Date: 2023-07-18 01:41:45.263098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5d7a9b7750'
down_revision = 'c93555bc419a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACCOUNT', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name', 'freight_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACCOUNT', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
