"""Adds index to truck driver FK in FREIGHT

Revision ID: fc92bfee2d73
Revises: 4f06d46925e7
Create Date: 2023-05-25 11:16:38.248585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc92bfee2d73'
down_revision = '4f06d46925e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FREIGHT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_FREIGHT_truck_driver_id'), ['truck_driver_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FREIGHT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_FREIGHT_truck_driver_id'))

    # ### end Alembic commands ###
