name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          cache: pip

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox -- --cov=src --cov-report=xml --junitxml=junittest.xml

      - name: Upload coverage reports to Codecov with GitHub Action
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: backend
          verbose: true

